spring.application.name=InfantMilkCare
server.port=8081

# MySQL Database Configuration
# BEFORE RUNNING: Create the database in MySQL: CREATE DATABASE infant_milk_care;
spring.datasource.url=jdbc:mysql://localhost:3306/infant_milk_care
spring.datasource.username=root
spring.datasource.password=MySQL@76310
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=true
